# Generated by Django 2.2 on 2019-04-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190414_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='job',
            name='description2',
            field=models.CharField(default=111, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description3',
            field=models.CharField(default=111, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
