# Generated by Django 2.2 on 2019-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190424_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description4',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='job',
            name='description5',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='job',
            name='description6',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='job',
            name='description7',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='job',
            name='description8',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description2',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description3',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
