# Generated by Django 2.2 on 2019-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190424_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
